### ISSUE TITLE
PkgResourcesDeprecationWarning

### ISSUE THREAD

**Issue by mehmetaliuluc** [ZENALC/algobot#172]
Hello,
UBUNTU20.04
not : Currently im using freqtade last version

/home/mehmet/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.1.36ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/home/mehmet/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.23ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/mehmet/algobot-master/algobot/__init__.py", line 4, in <module>
    from binance import Client
ModuleNotFoundError: No module named 'binance'

Could you please help me for solution

Br,

**Comment by mehmetaliuluc** [comment]
hi i found the problem . reinstall TA-LIB issue solved
