### ISSUE TITLE
Algobot Issue

### ISSUE THREAD

**Issue by space-mvc** [ZENALC/algobot#89]
**Describe the bug**

Hi is there an Binance Module available for Python3?

Currently i am getting this error on startup

`$ python -m algobot`

`
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/var/www/crypto3/algobot/algobot/__init__.py", line 4, in <module>
    from binance import Client
ModuleNotFoundError: No module named 'binance'`

This is happening on Ubuntu 20.04, Python3.8

**Comment by ZENALC** [comment]
doesn't look like you are in a venv? make sure you activate a venv and install all requirements

**Comment by space-mvc** [comment]
Ok sure yes that worked. I tested the documentation again from scratch and it worked fine.
